### PR TITLE
Code Refactor and Cleaning

### PR DESCRIPTION
**Pull request by alsharifnahas**
I have actually changed a lot in the styles.css, and index.html. I tried to make the main page look more cleaner in terms of size and positioning of the elements. I used flexboxes for the positioning, instead of the position attribute which made everything more easier to work with.

### CODE REVIEW

**Comment by Purukitto** [comment]
Thanks for the time you put into this, I will be reviewing the changes ASAP and update you!

**Comment by Purukitto** [comment]
For #5

**Review by Purukitto — COMMENTED** [review]
Will be testing the code in an deployed environment for expected behavior and update

**Comment by Purukitto** [comment]
You removed some @media statements and now the font is super small even in full screen browser window:
image

Nothing happens after I click on "start" button:
image

Even the error message(The username is invalid!) that popped up if I clicked on "start" does to appear due to this error : 
image

**Comment by alsharifnahas** [comment]
I stopped working on this anyways because you never answer. Have you looked at code in beginning, there's a a lot of basic html and css that you did not know how to use. The elements on the page had very weird positioning. Elements were just stacked on top of each other in index.html.

**Comment by Purukitto** [comment]
> I stopped working on this anyways because you never answer. Have you looked at code in beginning, there's a a lot of basic html and css that you did not know how to use. The elements on the page had very weird positioning. Elements were just stacked on top of each other in index.html.

I remember replying with proper screenshots after a day of you submitting the PR. As said so in the Issue description the website for compiled in a few hours with a random template, which explains the random html and css remains from the template, not having time to text and removed unneeded code and was exactly the reason why I opened the said issue.
Anyways I am closing this PR as your said you will not be working on it anymore, hope you have a nice day nevertheless

**Pull request closed without merging**
