### PR TITLE
Refactor and clean code

### PR DESCRIPTION
**Pull request by Troy96**
Hi @Purukitto,

I have made the changes in this PR. Please check if you need any more changes or is it good to go.

Thanks

### CODE REVIEW

**Comment by Purukitto** [comment]
Thanks for the time you put into this, I will be reviewing the changes ASAP and update you!

**Comment by Purukitto** [comment]
For #5

**Review by Purukitto — COMMENTED** [review]
All changes look sensible, will be looking if there are any behavior changes or not

**Comment by Troy96** [comment]
Sure @Purukitto.

**Pull request merged**
